<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operations [
        <!ELEMENT operations (operation)+>
        <!ELEMENT operation (gadget)+>
        <!ATTLIST operation
                name CDATA #REQUIRED>
        <!ELEMENT gadget (ins)+>
        <!ATTLIST gadget
                size CDATA #IMPLIED> <!-- size in bytes -->
        <!ELEMENT ins (dest|src)*>
        <!ATTLIST ins
                mnemonic CDATA #REQUIRED>
        <!ELEMENT dest (#PCDATA)>
        <!ATTLIST dest
                value CDATA #IMPLIED>
        <!ELEMENT src (#PCDATA)>
        ]>
<operations>
    <operation name="load_constant">
        <gadget size="1">
            <ins mnemonic="pop">
                <dest>reg</dest>
            </ins>
        </gadget>
        <gadget size="1">
            <ins mnemonic="popad" />
        </gadget>
    </operation>
</operations>